### ISSUE TITLE
Can't load the nuget package

### ISSUE THREAD

**Issue by yar1k0v** [Sopheakmorm/NLog.Telegram.Format.Core#1]
NuGet package version NLog.Telegram.Format.Core 1.0.3

**Comment by sopheakmorm** [comment]
hi @yar1k0v,
Could you provide me the detail output from `nuget`?

I think your problem related to the existing version of your application.
Please verify about the prerequisites of this package.
[Dependencies](https://drive.google.com/file/d/1seG_BoAxDfSzDDQfrgydJSov3BqMbQw8/view)

Hope you enjoy
